version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ecrm/main.go
    binary: ecrm
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
release:
  use_existing_draft: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
